[project]
name = "projeto-apc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pillow>=12.0.0",
    "psutil>=7.1.3",
    "rich[image]>=14.2.0",
]
